# Generated by Django 3.2.9 on 2021-11-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
