# Generated by Django 3.2.9 on 2021-11-22 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_car_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.car')),
            ],
        ),
    ]
