# Generated by Django 3.2.9 on 2021-11-22 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_carrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='rate',
        ),
    ]
