# Generated by Django 3.2.9 on 2021-11-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20211123_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrate',
            old_name='car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='carrate',
            old_name='rate',
            new_name='rating',
        ),
    ]
