# Generated by Django 3.2.9 on 2021-11-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_remove_car_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
