# Generated by Django 3.2.9 on 2021-11-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_car_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
    ]
